### ISSUE TITLE
Error: Unexpected Exception in open_reader()

### ISSUE THREAD

**Issue by OrkoHunter** [agarden/remove-pdf-watermark#2]
Hey, I tried this script (which more or less follows from an SO answer), but got an error like this

```
Error: Unexpected Exception in open_reader()
Unhandled Java Exception:
java.lang.NullPointerException
   at gnu.gcj.runtime.NameFinder.lookup(libgcj.so.14)
   at java.lang.Throwable.getStackTrace(libgcj.so.14)
   at java.lang.Throwable.stackTraceString(libgcj.so.14)
   at java.lang.Throwable.printStackTrace(libgcj.so.14)
   at java.lang.Throwable.printStackTrace(libgcj.so.14)
pdftk failed to uncompress a.pdf. Aborting.
```

I can't understand what's the issue here.

**Comment by agarden** [comment]
Was the PDF you were trying to work on called 'a.pdf'? If it isn't, then maybe there is a space in the filename and you need to quote it. If it is called that, then pdftk cannot read it for some reason. I have no insight into why that would be.

**Comment by OrkoHunter** [comment]
Yes the name of the filename is `a.pdf`. I am able to view it but maybe pdftk takes it as broken.

**Comment by agarden** [comment]
That stack trace is from pdftk. So, yes, it can't uncompress the file for whatever reason.
